eLEARNING_GROUP3/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineLearning.Services.Interfaces;

namespace OnlineLearning.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourseService _courseService;

        public CourseController(ICourseService courseService)
        {
            _courseService = courseService;
        }



        public async Task<IActionResult> Index()
        {
            var listCourse = await _courseService.GetAllCourseByStatusAsync();

            return View(listCourse);
        }


        [HttpGet("Course/DetailsCourse/{courseId}")]

        public async Task<IActionResult> DetailsCourse(long courseId)
        {
            var userIdString = HttpContext.Session.GetString("UserId");
            var checkPurchase = false;
            if (!string.IsNullOrEmpty(userIdString))
            {
                var userId = long.Parse(userIdString);
                checkPurchase = await _courseService.CheckPurchaseCourseAsync(userId, courseId);
            }

            var course = await _courseService.GetCourseDetailAsync(courseId);
            if (course == null)
            {
                return NotFound();
            }

            ViewBag.checkPurchase = checkPurchase;
            return View(course);
        }

    }
}

eLEARNING_GROUP3/Controllers/FAQsController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineLearning.Services.Interfaces;

namespace OnlineLearning.Controllers
{
    public class FAQsController : Controller
    {
        private readonly IFAQsService _faqsService;
        public FAQsController(IFAQsService faqsService)
        {
            _faqsService = faqsService;
        }

        public async Task<IActionResult> Index()
        {
            var faqs = await _faqsService.GetListFAQsToView();
            return View(faqs);
        }
    }
}

eLEARNING_GROUP3/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.IdentityModel.Tokens;
using OnlineLearning.Models.DTOs;
using OnlineLearning.Repositories.Interfaces;
using OnlineLearning.Services.Interfaces;

namespace OnlineLearning.Controllers
{
	public class ProfileController : Controller
	{
		private readonly IUserService _userService;
		private readonly IUserRepository _userRepo;

		public ProfileController(IUserService userService, IUserRepository userRepository)
		{
			_userService = userService;
			_userRepo = userRepository;
		}

		public async Task<ActionResult> Index()
		{
			var userIdString = HttpContext.Session.GetString("UserId");

			// Chưa đăng nhập
			if (string.IsNullOrEmpty(userIdString))
			{
				return RedirectToAction("Index", "Login");
			}

			// Lỗi xảy ra 
			if (!long.TryParse(userIdString, out long userId))
			{
				return RedirectToAction("Index", "Login");
			}
			var user = await _userService.GetUserByIdAsync(userId);
			if (user == null)
			{
				return NotFound();
			}
			// MAP: User to ProfileDTO
			var profileDto = new ProfileDTO
			{
				UserId = user.UserId,
				FullName = user.FullName,
				Phone = user.Phone,
				Email = user.Email,
				AvatarUrl = user.AvatarUrl,
				Gender = user.Gender,
				Dob = user.Dob
			};

			var message = TempData["message"] as String;
			if (!string.IsNullOrEmpty(message) || message != null)
			{
				TempData["message"] = message;
			}

			return View(profileDto);
		}

		// UPDATE PROFILE 
		[HttpPost]
		public async Task<IActionResult> EditProfile(ProfileDTO profile, IFormFile? avatarFile)
		{
			// Check login 
			string userId = HttpContext.Session.GetString("UserId");
			if (string.IsNullOrEmpty(userId))
			{
				return RedirectToAction("Index", "Login");
			}

			// Giữ nguyên email từ db
			var user = await _userService.GetUserByIdAsync(long.Parse(userId));
			if (user == null)
			{
				return NotFound();
			}
			profile.Email = user.Email;
			ModelState.Remove("Email"); // Loại bỏ lỗi validate Email

			// Check valid data
			if (!ModelState.IsValid)
			{
				return View("Index", profile);
			}
			var userByPhone = await _userRepo.GetByPhoneAsync(profile.Phone);

			if (userByPhone != null && !user.Equals(userByPhone)) // Nếu phone đã tồn tại
			{
				ModelState.AddModelError("Phone", "Phone already exists!");
				return View("Index", profile);
			}
			bool isProfileUpdated = await _userService.UpdateProfileAsync(profile);
			bool isAvatarUpdated = true; // Default nếu ko update avt
                                         // Có file ảnh -> cập nhật avatar

          

            if (avatarFile != null && avatarFile.Length > 0)
			{
				isAvatarUpdated = await _userService.ChangeAvatarAsync(profile.UserId, avatarFile);
            }
            var userEdit = await _userService.GetUserByIdAsync(long.Parse(userId));
            HttpContext.Session.SetString("Avatar", userEdit.AvatarUrl);




            // Xử lý thông báo
            TempData["message"] = (isProfileUpdated && isAvatarUpdated) ? "success" : "fail";

			return RedirectToAction("Index");
		}

		[HttpGet]
		public async Task<IActionResult> ChangePassword()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> ChangePassword(ChangePassDTO changePassDTO)
		{
			// Check login
			var userIdString = HttpContext.Session.GetString("UserId");
			if (string.IsNullOrEmpty(userIdString))
			{
				return RedirectToAction("Index", "Login");
			}

			// Check valid input
			if (!ModelState.IsValid)
			{
				return View("ChangePassword");
			}

			// Not found user info
			var userId = long.Parse(userIdString);
			var user = await _userService.GetUserByIdAsync(userId);
			if (user == null)
			{
				return NotFound();
			}

			// Check old pass
			if (!BCrypt.Net.BCrypt.Verify(changePassDTO.CurrentPassword, user.Password))
			{
				ModelState.AddModelError(nameof(changePassDTO.CurrentPassword), "Incorrect current password");
				return View("ChangePassword");
			}

			// Check cannot enter new pass same old pass
			if (BCrypt.Net.BCrypt.Verify(changePassDTO.NewPassword, user.Password))
			{
				ModelState.AddModelError(nameof(changePassDTO.NewPassword), "New password cannot be the same with current password");
				return View("ChangePassword");
			}

			// Change pass
			bool changeResult = await _userService.ChangePasswordAsync(userId, changePassDTO);
			if (!changeResult)
			{
				TempData["message"] = "update_failed";
				return View("ChangePassword");
			}
			TempData["message"] = "success";
			return RedirectToAction(nameof(ChangePassword));
		}
	}
}

eLEARNING_GROUP3/Views/Shared/_AdminHeader.cshtml
<header>
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
        <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
            <h2 class="m-0 text-primary"><i class="fa fa-book me-3"></i>eLEARNING</h2>
        </a>
        <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        @* <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
            <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
        </form> *@

        <a class="btn btn-primary" href="/TestAPI">Test API</a>

        <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarCollapse">
            <div class="navbar-nav p-4 p-lg-0">

                <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-item nav-link active">Home</a>

                <a asp-area="Admin" asp-controller="FAQs" asp-action="Index" class="nav-item nav-link">FAQ Management</a>

                <a asp-area="Admin" asp-controller="Dashboard" asp-action="Index" class="nav-item nav-link">Dashboard</a>

                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                    <div class="dropdown-menu fade-down m-0">
                        <a href="team.html" class="dropdown-item">Our Team</a>
                        <a href="testimonial.html" class="dropdown-item">Testimonial</a>
                        <a href="404.html" class="dropdown-item">404 Page</a>
                    </div>
                </div>
                <a href="contact.html" class="nav-item nav-link">Contact</a>

            </div>

            <div class="nav-item dropdown">
                <div class="ms-5 ps-5 me-4">
                    <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="@(Context.Session.GetString("Avatar") ?? Url.Content("/images/default-avatar.jpg"))" alt="mdo" width="50" height="50" class="rounded-circle">
                    </a>
                </div>
                <ul class="dropdown-menu dropdown-menu-end text-small fade-down" aria-labelledby="dropdownUser1">
                    <li><a class="dropdown-item" asp-area="" asp-controller="Profile" asp-action="Index">Profile</a></li>
                    <li><a class="dropdown-item" href="#">New project...</a></li>
                    <li><a class="dropdown-item" href="#">Settings</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a></li>
                </ul>
            </div>

        </div>
    </nav>
</header>

eLEARNING_GROUP3/Views/Shared/_GuestHeader.cshtml
<header>
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
        <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
            <h2 class="m-0 text-primary"><i class="fa fa-book me-3"></i>eLEARNING</h2>
        </a>
        <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <a class="btn btn-primary" href="/TestAPI">Test API</a>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto p-4 p-lg-0">

                <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-item nav-link active">Home</a>

                <a href="/" class="nav-item nav-link">About</a>

                <a asp-controller="Course" asp-action="Index" class="nav-item nav-link">Courses</a>

                <a asp-area="" asp-controller="FAQs" asp-action="Index" class="nav-item nav-link">FAQ</a>

                @* <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                    <div class="dropdown-menu fade-down m-0">
                        <a href="team.html" class="dropdown-item">Our Team</a>
                        <a href="testimonial.html" class="dropdown-item">Testimonial</a>
                        <a href="404.html" class="dropdown-item">404 Page</a>
                    </div>
                </div> *@
                <a href="/" class="nav-item nav-link">Contact</a>

            </div>
            <a asp-controller="Login" asp-action="Index" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block">Login<i class="fa fa-arrow-right ms-3"></i></a>

        </div>
    </nav>
</header>

eLEARNING_GROUP3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]eLearning - OnlineLearning</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/7.0.5/signalr.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlineLearning.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/izitoast/dist/css/iziToast.min.css">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/lib/animate/animate.min.css" rel="stylesheet" asp-append-version="true">
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" asp-append-version="true">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true">

    <!-- Template Stylesheet -->
    <link href="~/css/style.css" rel="stylesheet" asp-append-version="true">



</head>


<body>
    <header>
        @{
            var headerPartial = Context.Session.GetString("HeaderPartial") ?? "_GuestHeader";
        }
        <partial name="@headerPartial" />
    </header>



    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <footer>
        <div class="container-fluid bg-dark text-light footer1 pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
            <div class="container py-5">
                <div class="row g-5">
                    <div class="col-lg-3 col-md-6">
                        <h4 class="text-white mb-3">Quick Link</h4>
                        <a class="btn btn-link" href="">About Us</a>
                        <a class="btn btn-link" href="">Contact Us</a>
                        <a class="btn btn-link" href="">Privacy Policy</a>
                        <a class="btn btn-link" href="">Terms & Condition</a>
                        <a class="btn btn-link" href="">FAQs & Help</a>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h4 class="text-white mb-3">Contact</h4>
                        <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                        <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                        <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                        <div class="d-flex pt-2">
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h4 class="text-white mb-3">Gallery</h4>
                        <div class="row g-2 pt-2">
                            <div class="col-4">
                                <img class="img-fluid bg-light p-1" src="~/images/course-1.jpg" alt="">
                            </div>
                            <div class="col-4">
                                <img class="img-fluid bg-light p-1" src="~/images/course-2.jpg" alt="">
                            </div>
                            <div class="col-4">
                                <img class="img-fluid bg-light p-1" src="~/images/course-3.jpg" alt="">
                            </div>
                            <div class="col-4">
                                <img class="img-fluid bg-light p-1" src="~/images/course-2.jpg" alt="">
                            </div>
                            <div class="col-4">
                                <img class="img-fluid bg-light p-1" src="~/images/course-3.jpg" alt="">
                            </div>
                            <div class="col-4">
                                <img class="img-fluid bg-light p-1" src="~/images/course-1.jpg" alt="">
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h4 class="text-white mb-3">Newsletter</h4>
                        <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                        <div class="position-relative mx-auto" style="max-width: 400px;">
                            <input class="form-control border-0 w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                            <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="copyright">
                    <div class="row">
                        <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                            &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved.

                            <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                            Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a><br><br>
                            Distributed By <a class="border-bottom" href="https://themewagon.com">ThemeWagon</a>
                        </div>
                        <div class="col-md-6 text-center text-md-end">
                            <div class="footer-menu">
                                <a href="">Home</a>
                                <a href="">Cookies</a>
                                <a href="">Help</a>
                                <a href="">FAQs</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </footer>




    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="lib/wow/wow.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/waypoints/waypoints.min.js"></script>
    <script src="lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Template Javascript -->
    <script src="js/main.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/izitoast/dist/js/iziToast.min.js"></script>
    <script>
        function showToast(type, title, message) {
            iziToast[type]({
                title: title,
                message: message,
                position: 'topRight'
            });
        }
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

eLEARNING_GROUP3/Views/Shared/_MenteeHeader.cshtml
<header>
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
        <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
            <h2 class="m-0 text-primary"><i class="fa fa-book me-3"></i>eLEARNING</h2>
        </a>
        <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        @* 
        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
            <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
        </form> *@
        <a class="btn btn-primary" href="/TestAPI">Test API</a>

        <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarCollapse">
            <div class="navbar-nav p-4 p-lg-0">

                <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-item nav-link active">Home</a>

                <a asp-controller="Course" asp-action="Index" class="nav-item nav-link">Courses</a>

                <a href="about.html" class="nav-item nav-link">About</a>

                <a asp-area="" asp-controller="FAQs" asp-action="Index" class="nav-item nav-link">FAQ</a>

                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                    <div class="dropdown-menu fade-down m-0">
                        <a href="team.html" class="dropdown-item">Our Team</a>
                        <a href="testimonial.html" class="dropdown-item">Testimonial</a>
                        <a href="404.html" class="dropdown-item">404 Page</a>
                    </div>
                </div>
                <a href="contact.html" class="nav-item nav-link">Contact</a>

            </div>

            <div class="nav-item dropdown">
                <div class="ms-5 ps-5 me-4">
                    <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="@(Context.Session.GetString("Avatar") ?? Url.Content("/images/default-avatar.jpg"))" alt="mdo" width="50" height="50" class="rounded-circle">
                    </a>
                </div>
                <ul class="dropdown-menu dropdown-menu-end text-small fade-down" aria-labelledby="dropdownUser1">
                    <li><a class="dropdown-item" asp-area="" asp-controller="Profile" asp-action="Index">Profile</a></li>
                    <li><a class="dropdown-item" href="#">New project...</a></li>
                    <li><a class="dropdown-item" href="#">Settings</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a></li>
                </ul>
            </div>

        </div>
    </nav>
</header>

eLEARNING_GROUP3/Views/Shared/_MentorHeader.cshtml
<header>
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
        <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
            <h2 class="m-0 text-primary"><i class="fa fa-book me-3"></i>eLEARNING</h2>
        </a>
        <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        @* 
        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
            <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
        </form> *@
        <a class="btn btn-primary" href="/TestAPI">Test API</a>

        <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarCollapse">
            <div class="navbar-nav p-4 p-lg-0">

                <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-item nav-link active">Home</a>

                <a asp-controller="Course" asp-action="Index" class="nav-item nav-link">Courses</a>

                <a href="about.html" class="nav-item nav-link">About</a>

                <a asp-area="" asp-controller="FAQs" asp-action="Index" class="nav-item nav-link">FAQ</a>

                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                    <div class="dropdown-menu fade-down m-0">
                        <a href="team.html" class="dropdown-item">Our Team</a>
                        <a href="testimonial.html" class="dropdown-item">Testimonial</a>
                        <a href="404.html" class="dropdown-item">404 Page</a>
                    </div>
                </div>
                <a href="contact.html" class="nav-item nav-link">Contact</a>

            </div>

            <div class="nav-item dropdown">
                <div class="ms-5 ps-5 me-4">
                    <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="@(Context.Session.GetString("Avatar") ?? Url.Content("/images/default-avatar.jpg"))" alt="mdo" width="50" height="50" class="rounded-circle">
                    </a>
                </div>
                <ul class="dropdown-menu dropdown-menu-end text-small fade-down" aria-labelledby="dropdownUser1">
                    <li><a class="dropdown-item" asp-area="" asp-controller="Profile" asp-action="Index">Profile</a></li>
                    <li><a class="dropdown-item" href="#">Settings</a></li>
                    <li><a class="dropdown-item" href="#">My Project Mentor</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a></li>
                </ul>
            </div>

        </div>
    </nav>
</header>