eLEARNING_GROUP3/Models/Domains/CourseModels/Module.cs
using System.ComponentModel.DataAnnotations;
using OnlineLearning.Enums;
using OnlineLearning.Models.Domains.CourseModels.LessonModels;
using OnlineLearning.Models.Domains.CourseModels.QuizModels;

namespace OnlineLearning.Models.Domains.CourseModels
{
    public class Module
    {
        [Key]
        public long ModuleId { get; set; }

        [Required]
        [StringLength(255)]
        public string ModuleName { get; set; } = null!;

        public long CourseId { get; set; }

        [Required]
        public int ModuleNumber { get; set; }

        [Required]
        public DateTime CreatedAt { get; set; } = DateTime.Now;

        public DateTime? UpdatedAt { get; set; }

        [Required]
        public CommonStatus Status { get; set; }

        public virtual Course Course { get; set; } = null!;
        public virtual ICollection<Lesson> Lessons { get; set; } = new List<Lesson>();
        public virtual ICollection<Quiz> Quizzes { get; set; } = new List<Quiz>();
    }
}

eLEARNING_GROUP3/Areas/Mentor/Controllers/ModulesController.cs
using Humanizer;
using Microsoft.AspNetCore.Mvc;
using OnlineLearning.Models.Domains.CourseModels;
using OnlineLearning.Models.DTOs;
using OnlineLearning.Services.Interfaces;

namespace OnlineLearning.Areas.Mentor.Controllers
{
    [Area("Mentor")]
    public class ModulesController : Controller
    {

        private readonly IModuleService _moduleService;

        public ModulesController(IModuleService moduleService)
        {
            _moduleService = moduleService;
        }

        public async Task<IActionResult> Index(long courseId)
        {
            int nextModuleNumber = await _moduleService.GetNextModuleNumberAsync(courseId);

            var model = new ModuleDto
            {
                CourseId = courseId,
                ModuleNumber = nextModuleNumber
            };
            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> AddModules(ModuleDto model)
        {
            if (!ModelState.IsValid)
            {
                return View(model); // Trả về view nếu validation không hợp lệ
            }
            if (model.ModuleName.Length > 255)
            {
                ModelState.AddModelError("ModuleName", "ModuleName không được vượt quá 255 ký tự!");
            }

            var module = new Module
            {
                CourseId = model.CourseId,
                ModuleName = model.ModuleName,
                ModuleNumber = model.ModuleNumber
            };

            await _moduleService.AddModuleAsync(module);

            return RedirectToAction("CourseEdit", "Course", new { id = model.CourseId });
        }



    }
}

eLEARNING_GROUP3/Areas/Mentor/Views/Modules/Index.cshtml
@model ModuleDto
@{
    Layout = "_Layout";
}

    <div class="container">
    <h3 style=" margin-top: 50px; margin-bottom: 50px;">
        Add New Module
    </h3>

        <form asp-controller="Modules" asp-action="AddModules" method="post" >

            <div class="mb-3">
                <input type="hidden" class="form-control" asp-for="CourseId">
            </div>

            <div class="mb-3">
                <label class="form-label">Module Name</label>
                <input type="text" asp-for="ModuleName" class="form-control" placeholder="Enter module name">
            </div>

            <div class="mb-3">
                <label class="form-label">Module Number</label>
                <input type="text" asp-for="ModuleNumber" class="form-control" readonly>
            </div>

            <div class="d-flex justify-content-end">
            <a asp-controller="Course" asp-action="CourseEdit" asp-route-id="@Model.CourseId" class="btn btn-light">Back</a>
            <button type="submit" class="btn btn-submit">Add Module</button>
            </div>
        </form>

    </div>